import React from 'react';
import Link from './link';

const Footer = () => {
  return (
    <footer class="site-footer">
      <p>Based on <Link to="https://uptimerobot.com/" text="UptimeRobot" />  API, the detection frequency is 5 minutes.</p>
      <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.<br />This page is transplanted from <a href="https://github.com/yb/uptime-status">yb/uptime-status</a>, modified by <a href="https://baoshuo.ren/?utm-source=status">Ren Baoshuo</a>.</span>
      </footer>
  );
}

export default Footer;

