import React from 'react';
import Link from './link';

const Footer = () => {
  return (
    <footer class="site-footer">
      <p>基于 <Link to="https://uptimerobot.com/" text="UptimeRobot" /> 接口制作，检测频率 5 分钟。</p>
      <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.<br />This page is transplanted from <a href="https://github.com/yb/uptime-status">yb/uptime-status</a>, modified by <a href="https://baoshuo.ren/?utm-source=status">Ren Baoshuo</a>.</span>
      </footer>
  );
}

export default Footer;

